/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * compute_q_vec.cpp
 *
 * Code generation for function 'compute_q_vec'
 *
 */

/* Include files */
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "computeSLQTrajHoop.h"
#include "compute_q_vec.h"

/* Function Definitions */
void compute_q_vec(real_T t, const real_T in2[12], const real_T in4[12], const
                   real_T in6[12], real_T t_wp, real_T q_vec[12])
{
  real_T t4;

  /* COMPUTE_Q_VEC */
  /*     Q_VEC = COMPUTE_Q_VEC(T,IN2,IN3,IN4,IN5,IN6,T_WP) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.2. */
  /*     10-Dec-2018 00:20:13 */
  t4 = t - t_wp;
  t4 = muDoubleScalarExp(-(t4 * t4 * 100.0));
  q_vec[0] = (in2[0] * 20.0 - in4[0] * 20.0) + t4 * (in2[0] * 112837.9167095513
    - in6[0] * 112837.9167095513);
  q_vec[1] = (in2[1] * 20.0 - in4[1] * 20.0) - t4 * (in6[1] * 112837.9167095513
    - in2[1] * 112837.9167095513);
  q_vec[2] = (in2[2] * 20.0 - in4[2] * 20.0) - t4 * (in6[2] * 112837.9167095513
    - in2[2] * 112837.9167095513);
  q_vec[3] = (in2[3] * 20.0 - in4[3] * 20.0) + t4 * (in2[3] * 1128.3791670955129
    - in6[3] * 1128.3791670955129);
  q_vec[4] = (in4[4] * -20.0 + in2[4] * 20.0) + t4 * (in2[4] *
    1128.3791670955129 - in6[4] * 1128.3791670955129);
  q_vec[5] = (in4[5] * -20.0 + in2[5] * 20.0) + t4 * (in2[5] *
    1128.3791670955129 - in6[5] * 1128.3791670955129);
  q_vec[6] = (in2[6] * 20.0 - in4[6] * 20.0) + t4 * (in2[6] * 1128.3791670955129
    - in6[6] * 1128.3791670955129);
  q_vec[7] = (in2[7] * 20.0 - in4[7] * 20.0) + t4 * (in2[7] * 1128.3791670955129
    - in6[7] * 1128.3791670955129);
  q_vec[8] = (in2[8] * 20.0 - in4[8] * 20.0) + t4 * (in2[8] * 1128.3791670955129
    - in6[8] * 1128.3791670955129);
  q_vec[9] = in2[9] * 20.0 - in4[9] * 20.0;
  q_vec[10] = in2[10] * 20.0 - in4[10] * 20.0;
  q_vec[11] = in2[11] * 20.0 - in4[11] * 20.0;
}

/* End of code generation (compute_q_vec.cpp) */
