/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * compute_r_vec.cpp
 *
 * Code generation for function 'compute_r_vec'
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "computeSLQTrajHoop.h"
#include "compute_r_vec.h"

/* Function Definitions */
void compute_r_vec(const real_T in3[4], const real_T in5[4], real_T r[4])
{
  /* COMPUTE_R_VEC */
  /*     R = COMPUTE_R_VEC(T,IN2,IN3,IN4,IN5,IN6,T_WP) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.1. */
  /*     03-Dec-2018 16:04:05 */
  r[0] = in3[0] * 20000.0 - in5[0] * 20000.0;
  r[1] = in3[1] * 20000.0 - in5[1] * 20000.0;
  r[2] = in3[2] * 20000.0 - in5[2] * 20000.0;
  r[3] = in3[3] * 20000.0 - in5[3] * 20000.0;
}

/* End of code generation (compute_r_vec.cpp) */
