/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * compute_B.cpp
 *
 * Code generation for function 'compute_B'
 *
 */

/* Include files */
#include <string.h>
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "computeSLQTrajHoop.h"
#include "compute_B.h"

/* Function Definitions */
void compute_B(const real_T in1[12], real_T B[48])
{
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t6;
  real_T t7;
  real_T t8;
  real_T t9;
  real_T t10;
  real_T t11_tmp;
  real_T t12;
  real_T t13;
  real_T t16_tmp;
  real_T t16;
  real_T t18;
  real_T t24;
  real_T t19;
  real_T t23_tmp;
  real_T t23;

  /* COMPUTE_B */
  /*     B = COMPUTE_B(IN1,IN2) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.1. */
  /*     03-Dec-2018 17:53:26 */
  /*  Version 1. Inputs are (q,u). */
  t2 = muDoubleScalarCos(in1[5]);
  t3 = muDoubleScalarSin(in1[3]);
  t4 = muDoubleScalarCos(in1[3]);
  t5 = muDoubleScalarSin(in1[5]);
  t6 = muDoubleScalarSin(in1[4]);
  t7 = muDoubleScalarCos(in1[4]);
  t8 = t4 * t4;
  t9 = t3 * t3;
  t10 = t8 * t8;
  t11_tmp = t7 * t7;
  t12 = t9 * t9;
  t13 = t6 * t6;
  t16_tmp = t8 * t9;
  t16 = 1.0 / ((t10 + t12) + t16_tmp * 2.0);
  t18 = 1.0 / t7;
  t24 = t3 * t4;
  t19 = t24 * t6 * t16 * t18 * 0.41349226839398467;
  t23_tmp = t16 * (1.0 / t11_tmp);
  t23 = t23_tmp * (t6 * t8 * 2.2829065080801941E+35 + t6 * t9 *
                   4.0294675112499823E+35) * 2.3674653656159082E-36;
  t24 = t24 * t16 * t18 * 0.41349226839398467;
  B[0] = 0.0;
  B[1] = 0.0;
  B[2] = 0.0;
  B[3] = 0.0;
  B[4] = 0.0;
  B[5] = 0.0;
  B[6] = t3 * t5 * 0.5865102639296188 + t2 * t4 * t6 * 0.5865102639296188;
  B[7] = t2 * t3 * -0.5865102639296188 + t4 * t5 * t6 * 0.5865102639296188;
  B[8] = t4 * t7 * 0.5865102639296188;
  memset(&B[9], 0, 12U * sizeof(real_T));
  B[21] = t23_tmp * ((((t8 * t13 * 2.2829065080801941E+35 + t10 * t11_tmp *
                        4.0294675112499823E+35) + t9 * t13 *
                       4.0294675112499823E+35) + t11_tmp * t12 *
                      4.0294675112499823E+35) + t16_tmp * t11_tmp *
                     8.0589350224999631E+35) * 2.3674653656159082E-36;
  B[22] = t19;
  B[23] = t23;
  memset(&B[24], 0, 9U * sizeof(real_T));
  B[33] = t19;
  B[34] = t16 * t18 * (t7 * t8 * 4.0294675112499823E+35 + t7 * t9 *
                       2.2829065080801941E+35) * 2.3674653656159082E-36;
  B[35] = t24;
  memset(&B[36], 0, 9U * sizeof(real_T));
  B[45] = t23;
  B[46] = t24;
  B[47] = t23_tmp * (t8 * 2.2829065080801941E+35 + t9 * 4.0294675112499823E+35) *
    2.3674653656159082E-36;
}

/* End of code generation (compute_B.cpp) */
