/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * getDynSys.cpp
 *
 * Code generation for function 'getDynSys'
 *
 */

/* Include files */
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "computeSLQTrajHoop.h"
#include "getDynSys.h"

/* Function Definitions */
void getDynSys(const real_T in1[12], const real_T in2[4], real_T dstates[12])
{
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t6;
  real_T t7;
  real_T t8;
  real_T t9;
  real_T t10;
  real_T t11_tmp;
  real_T t12;
  real_T t13;
  real_T t14;
  real_T t15;
  real_T t16;
  real_T t19_tmp;
  real_T t19;
  real_T dstates_tmp_tmp;
  real_T dstates_tmp;
  real_T b_dstates_tmp;
  real_T c_dstates_tmp;
  real_T d_dstates_tmp;
  real_T e_dstates_tmp;
  real_T b_dstates_tmp_tmp;
  real_T f_dstates_tmp;
  real_T c_dstates_tmp_tmp;
  real_T g_dstates_tmp;
  real_T h_dstates_tmp;
  real_T i_dstates_tmp;
  real_T j_dstates_tmp;
  real_T k_dstates_tmp;
  real_T l_dstates_tmp;
  real_T d_dstates_tmp_tmp;
  real_T e_dstates_tmp_tmp;
  real_T m_dstates_tmp;
  real_T n_dstates_tmp;
  real_T o_dstates_tmp;
  real_T p_dstates_tmp;
  real_T q_dstates_tmp;
  real_T r_dstates_tmp;

  /* GETDYNSYS */
  /*     DSTATES = GETDYNSYS(IN1,IN2) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.1. */
  /*     03-Dec-2018 17:53:19 */
  t2 = muDoubleScalarCos(in1[5]);
  t3 = muDoubleScalarSin(in1[3]);
  t4 = muDoubleScalarCos(in1[3]);
  t5 = muDoubleScalarSin(in1[5]);
  t6 = muDoubleScalarSin(in1[4]);
  t7 = muDoubleScalarCos(in1[4]);
  t8 = t4 * t4;
  t9 = t3 * t3;
  t10 = t8 * t8;
  t11_tmp = t7 * t7;
  t12 = t9 * t9;
  t13 = t6 * t6;
  t14 = in1[11] * in1[11];
  t15 = t11_tmp * t11_tmp;
  t16 = in1[10] * in1[10];
  t19_tmp = t8 * t9;
  t19 = 1.0 / ((t10 + t12) + t19_tmp * 2.0);
  dstates[0] = in1[6];
  dstates[1] = in1[7];
  dstates[2] = in1[8];
  dstates[3] = in1[9];
  dstates[4] = in1[10];
  dstates[5] = in1[11];
  dstates[6] = in1[6] * -2.6979472140762461E-5 + in2[0] * (t3 * t5 + t2 * t4 *
    t6) * 29.325513196480941;
  dstates[7] = in1[7] * -2.6686217008797659E-5 - in2[0] * (t2 * t3 - t4 * t5 *
    t6) * 29.325513196480941;
  dstates[8] = (in1[8] * -3.0205278592375372E-5 + in2[0] * t4 * t7 *
                29.325513196480941) - 9.81;
  t2 = in1[9] * in1[10];
  t5 = t2 * t6 * t7;
  dstates_tmp_tmp = in1[11] * in1[10];
  dstates_tmp = dstates_tmp_tmp * t7;
  b_dstates_tmp = dstates_tmp * t10;
  c_dstates_tmp = t3 * t4;
  d_dstates_tmp = c_dstates_tmp * t10;
  e_dstates_tmp = c_dstates_tmp * t11_tmp;
  b_dstates_tmp_tmp = in1[10] * in1[5];
  f_dstates_tmp = b_dstates_tmp_tmp * t7;
  c_dstates_tmp_tmp = c_dstates_tmp * t8;
  g_dstates_tmp = c_dstates_tmp_tmp * t9;
  h_dstates_tmp = in1[9] * in1[11];
  i_dstates_tmp = t5 * t8;
  j_dstates_tmp = dstates_tmp * t8;
  k_dstates_tmp = j_dstates_tmp * t9;
  l_dstates_tmp = dstates_tmp * t9;
  d_dstates_tmp_tmp = h_dstates_tmp * t3;
  e_dstates_tmp_tmp = d_dstates_tmp_tmp * t4;
  m_dstates_tmp = e_dstates_tmp_tmp * t6;
  n_dstates_tmp = t6 * t8;
  o_dstates_tmp = t6 * t9;
  p_dstates_tmp = c_dstates_tmp * t6;
  q_dstates_tmp = h_dstates_tmp * t4;
  r_dstates_tmp = t19 * (1.0 / t11_tmp);
  dstates[9] = r_dstates_tmp * (((((((((((((((((((((((((((((((((((((((t8 * t13 *
    in2[1] * 2.2829065080801941E+35 + t10 * t11_tmp * in2[1] *
    4.0294675112499823E+35) + t9 * t13 * in2[1] * 4.0294675112499823E+35) +
    t11_tmp * t12 * in2[1] * 4.0294675112499823E+35) + n_dstates_tmp * in2[3] *
    2.2829065080801941E+35) + o_dstates_tmp * in2[3] * 4.0294675112499823E+35) +
    t19_tmp * t11_tmp * in2[1] * 8.0589350224999631E+35) + i_dstates_tmp *
    4.7861557702365728E+33) + t5 * t9 * 8.4478532571043123E+33) + t5 * t10 *
    3.6616974868677389E+33) - t5 * t12 * 6.4631166485075149E+33) - j_dstates_tmp
    * t13 * 4.7861557702365728E+33) + b_dstates_tmp * t11_tmp *
    8.4478532571043123E+33) - l_dstates_tmp * t13 * 8.4478532571043123E+33) +
    b_dstates_tmp * t13 * 4.7861557702365728E+33) + dstates_tmp * t11_tmp * t12 *
    8.4478532571043123E+33) + dstates_tmp * t12 * t13 * 2.3358823162716139E+34)
    + f_dstates_tmp * t10 * t13 * 8.4478532571043123E+33) + d_dstates_tmp *
    t11_tmp * t16 * 6.4631166485075149E+33) + e_dstates_tmp * t13 * t14 *
    3.6616974868677389E+33) - d_dstates_tmp * t14 * t15 * 6.4631166485075149E+33)
    + e_dstates_tmp * t12 * t16 * 6.4631166485075149E+33) - c_dstates_tmp * t12 *
    t14 * t15 * 6.4631166485075149E+33) + p_dstates_tmp * t7 * in2[2] *
    1.7465610031697871E+35) + f_dstates_tmp * t8 * t9 * t13 *
    1.4910969905611829E+34) + g_dstates_tmp * t11_tmp * t16 *
    1.292623329701503E+34) - g_dstates_tmp * t14 * t15 * 1.292623329701503E+34)
    - c_dstates_tmp_tmp * t11_tmp * t13 * t14 * 1.012481413537525E+34) -
    c_dstates_tmp * t9 * t11_tmp * t13 * t14 * 1.012481413537525E+34) +
    m_dstates_tmp * t11_tmp * 3.6616974868677389E+33) - q_dstates_tmp * t6 * t9 *
    t11_tmp * 2.801419161639776E+33) - i_dstates_tmp * t9 *
    2.801419161639776E+33) + k_dstates_tmp * t11_tmp * 1.689570651420862E+34) -
    j_dstates_tmp * t10 * t11_tmp * 6.4631166485075149E+33) + k_dstates_tmp *
    t13 * 2.16818622844452E+34) - l_dstates_tmp * t10 * t11_tmp *
    6.4631166485075149E+33) + j_dstates_tmp * t11_tmp * t12 *
    6.4631166485075149E+33) + l_dstates_tmp * t11_tmp * t12 *
    6.4631166485075149E+33) + m_dstates_tmp * t8 * t11_tmp *
    1.012481413537525E+34) + m_dstates_tmp * t9 * t11_tmp *
    1.292623329701503E+34) * 1.183732682807954E-34;
  t5 = h_dstates_tmp * t8;
  dstates_tmp = t2 * t3 * t4 * t7;
  b_dstates_tmp = dstates_tmp_tmp * t3 * t4 * t6 * t7;
  dstates[10] = t19 * (((((((((((((((((((((c_dstates_tmp * in2[3] *
    1.7465610031697871E+35 + t7 * t8 * in2[2] * 4.0294675112499823E+35) + t7 *
    t9 * in2[2] * 2.2829065080801941E+35) + t5 * t11_tmp *
    8.4478532571043123E+33) + h_dstates_tmp * t9 * t11_tmp *
    4.7861557702365728E+33) + h_dstates_tmp * t10 * t11_tmp *
    6.4631166485075149E+33) + n_dstates_tmp * t11_tmp * t14 *
    8.4478532571043123E+33) + o_dstates_tmp * t11_tmp * t14 *
    4.7861557702365728E+33) - t6 * t10 * t11_tmp * t14 * 1.4910969905611829E+34)
    - t6 * t11_tmp * t12 * t14 * 4.7861557702365728E+33) + p_dstates_tmp * in2[1]
    * 1.7465610031697871E+35) - d_dstates_tmp_tmp * t8 * t11_tmp *
    6.4631166485075149E+33) - d_dstates_tmp_tmp * t9 * t11_tmp *
    3.6616974868677389E+33) + t5 * t9 * t11_tmp * 9.2645358101472915E+33) +
    dstates_tmp * 3.6616974868677389E+33) - n_dstates_tmp * t9 * t11_tmp * t14 *
    1.96971256758484E+34) - dstates_tmp * t8 * 1.012481413537525E+34) -
    dstates_tmp * t9 * 1.012481413537525E+34) - b_dstates_tmp *
    3.6616974868677389E+33) + b_dstates_tmp * t8 * 3.6616974868677389E+33) +
                        b_dstates_tmp * t9 * 1.012481413537525E+34) +
                       b_dstates_tmp_tmp * t3 * t4 * t6 * t7 * t8 *
                       6.4631166485075149E+33) * 1.183732682807954E-34 / t7;
  t5 = t2 * t7;
  dstates_tmp = t5 * t8;
  b_dstates_tmp = dstates_tmp_tmp * t6 * t7;
  d_dstates_tmp = b_dstates_tmp_tmp * t6 * t7;
  e_dstates_tmp = b_dstates_tmp * t8;
  dstates[11] = r_dstates_tmp * (((((((((((((((((((((((t8 * in2[3] *
    2.2829065080801941E+35 + t9 * in2[3] * 4.0294675112499823E+35) +
    n_dstates_tmp * in2[1] * 2.2829065080801941E+35) + o_dstates_tmp * in2[1] *
    4.0294675112499823E+35) + dstates_tmp * 4.7861557702365728E+33) + t5 * t9 *
    8.4478532571043123E+33) + t5 * t10 * 3.6616974868677389E+33) - t5 * t12 *
    6.4631166485075149E+33) + c_dstates_tmp * t7 * in2[2] *
    1.7465610031697871E+35) + e_dstates_tmp_tmp * t11_tmp *
    3.6616974868677389E+33) - q_dstates_tmp * t9 * t11_tmp *
    2.801419161639776E+33) - dstates_tmp * t9 * 2.801419161639776E+33) -
    e_dstates_tmp * 4.7861557702365728E+33) - b_dstates_tmp * t9 *
    8.4478532571043123E+33) + b_dstates_tmp * t10 * 4.7861557702365728E+33) +
    b_dstates_tmp * t12 * 2.3358823162716139E+34) + d_dstates_tmp * t10 *
    8.4478532571043123E+33) + p_dstates_tmp * t11_tmp * t14 *
    3.6616974868677389E+33) + d_dstates_tmp * t8 * t9 * 1.4910969905611829E+34)
    - p_dstates_tmp * t8 * t11_tmp * t14 * 1.012481413537525E+34) -
    p_dstates_tmp * t9 * t11_tmp * t14 * 1.012481413537525E+34) +
    e_dstates_tmp_tmp * t8 * t11_tmp * 1.012481413537525E+34) +
    e_dstates_tmp_tmp * t9 * t11_tmp * 1.292623329701503E+34) + e_dstates_tmp *
    t9 * 2.16818622844452E+34) * 1.183732682807954E-34;
}

/* End of code generation (getDynSys.cpp) */
