/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * compute_q_vec.cpp
 *
 * Code generation for function 'compute_q_vec'
 *
 */

/* Include files */
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "slqSolve.h"
#include "compute_q_vec.h"

/* Function Definitions */
void compute_q_vec(real_T t, const real_T in2[12], const real_T in4[12], const
                   real_T in6[12], real_T t_wp, real_T q_vec[12])
{
  real_T t2;

  /* COMPUTE_Q_VEC */
  /*     Q_VEC = COMPUTE_Q_VEC(T,IN2,IN3,IN4,IN5,IN6,T_WP) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.1. */
  /*     07-Nov-2018 09:38:17 */
  t2 = t - t_wp;
  t2 = muDoubleScalarExp(-(t2 * t2 * 100.0));
  q_vec[0] = (in2[0] * 2.0 - in4[0] * 2.0) + t2 * (in2[0] * 11283.79167095513 -
    in6[0] * 11283.79167095513);
  q_vec[1] = (in2[1] * 2.0 - in4[1] * 2.0) - t2 * (in6[1] * 11283.79167095513 -
    in2[1] * 11283.79167095513);
  q_vec[2] = (in2[2] * 2.0 - in4[2] * 2.0) - t2 * (in6[2] * 11283.79167095513 -
    in2[2] * 11283.79167095513);
  q_vec[3] = (in2[3] * 2.0 - in4[3] * 2.0) + t2 * (in2[3] * 11283.79167095513 -
    in6[3] * 11283.79167095513);
  q_vec[4] = (in2[4] * 2.0 - in4[4] * 2.0) + t2 * (in2[4] * 11283.79167095513 -
    in6[4] * 11283.79167095513);
  q_vec[5] = (in2[5] * 2.0 - in4[5] * 2.0) - t2 * (in6[5] * 11283.79167095513 -
    in2[5] * 11283.79167095513);
  q_vec[6] = (in2[6] * 2.0 - in4[6] * 2.0) + t2 * (in2[6] * 11283.79167095513 -
    in6[6] * 11283.79167095513);
  q_vec[7] = (in2[7] * 2.0 - in4[7] * 2.0) + t2 * (in2[7] * 11283.79167095513 -
    in6[7] * 11283.79167095513);
  q_vec[8] = (in2[8] * 2.0 - in4[8] * 2.0) + t2 * (in2[8] * 11283.79167095513 -
    in6[8] * 11283.79167095513);
  q_vec[9] = (in2[9] * 2.0 - in4[9] * 2.0) + t2 * (in2[9] * 11283.79167095513 -
    in6[9] * 11283.79167095513);
  q_vec[10] = (in2[10] * 2.0 - in4[10] * 2.0) + t2 * (in2[10] *
    11283.79167095513 - in6[10] * 11283.79167095513);
  q_vec[11] = t2 * (in2[11] * 11283.79167095513 - in6[11] * 11283.79167095513);
}

/* End of code generation (compute_q_vec.cpp) */
