/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * compute_r_vec.cpp
 *
 * Code generation for function 'compute_r_vec'
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "slqSolve.h"
#include "compute_r_vec.h"

/* Function Definitions */
void compute_r_vec(const real_T in3[6], const real_T in5[6], real_T r[6])
{
  /* COMPUTE_R_VEC */
  /*     R = COMPUTE_R_VEC(T,IN2,IN3,IN4,IN5,IN6,T_WP) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.1. */
  /*     07-Nov-2018 09:38:17 */
  r[0] = in3[0] - in5[0];
  r[1] = in3[1] - in5[1];
  r[2] = in3[2] - in5[2];
  r[3] = in3[3] - in5[3];
  r[4] = in3[4] - in5[4];
  r[5] = in3[5] - in5[5];
}

/* End of code generation (compute_r_vec.cpp) */
