function R = compute_R_mat(in1,in2)
%COMPUTE_R_MAT
%    R = COMPUTE_R_MAT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    29-Oct-2018 23:23:04

R = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0],[6,6]);
