function L = compute_L(t,in2,in3,in4,in5,in6,t_wp)
%COMPUTE_L
%    L = COMPUTE_L(T,IN2,IN3,IN4,IN5,IN6,T_WP)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    13-Nov-2018 10:35:47

dphi = in2(10,:);
dpsi = in2(12,:);
dtheta = in2(11,:);
dx = in2(7,:);
dy = in2(8,:);
dz = in2(9,:);
phi = in2(4,:);
psi = in2(6,:);
theta = in2(5,:);
u1 = in3(1,:);
u2 = in3(2,:);
u3 = in3(3,:);
u4 = in3(4,:);
u1b = in5(1,:);
u2b = in5(2,:);
u3b = in5(3,:);
u4b = in5(4,:);
x = in2(1,:);
x_wp_1 = in6(1,:);
x_wp_2 = in6(2,:);
x_wp_3 = in6(3,:);
x_wp_4 = in6(4,:);
x_wp_5 = in6(5,:);
x_wp_6 = in6(6,:);
x_wp_7 = in6(7,:);
x_wp_8 = in6(8,:);
x_wp_9 = in6(9,:);
x_wp_10 = in6(10,:);
x_wp_11 = in6(11,:);
x_wp_12 = in6(12,:);
y = in2(2,:);
z = in2(3,:);
t2 = phi-x_wp_4;
t3 = psi-x_wp_6;
t4 = theta-x_wp_5;
t5 = x-x_wp_1;
t6 = x_wp_2-y;
t7 = x_wp_3-z;
t8 = t-t_wp;
t9 = dphi-x_wp_10;
t10 = dpsi-x_wp_12;
t11 = dtheta-x_wp_11;
t12 = dx-x_wp_7;
t13 = dy-x_wp_8;
t14 = dz-x_wp_9;
L = (u1.*(1.0./1.0e1)-u1b.*(1.0./1.0e1)).*(u1-u1b)+(u2.*(1.0./1.0e1)-u2b.*(1.0./1.0e1)).*(u2-u2b)+(u3.*(1.0./1.0e1)-u3b.*(1.0./1.0e1)).*(u3-u3b)+(u4.*(1.0./1.0e1)-u4b.*(1.0./1.0e1)).*(u4-u4b)+exp(t8.^2.*(-1.0./2.0)).*(t5.*(x.*1.0e3-x_wp_1.*1.0e3).*3.989422804014327e-1+t6.*(x_wp_2.*1.0e3-y.*1.0e3).*3.989422804014327e-1+t7.*(x_wp_3.*1.0e3-z.*1.0e3).*3.989422804014327e-1)+t2.^2+t3.^2+t4.^2+t5.^2+t6.^2+t7.^2+t9.^2+t10.^2+t11.^2+t12.^2+t13.^2+t14.^2;
