function R = compute_R(in1,in2)
%COMPUTE_R
%    R = COMPUTE_R(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    27-Oct-2018 20:33:00

R = reshape([2.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0],[6,6]);
