function qN = compute_qN(in1,in2)
%COMPUTE_QN
%    QN = COMPUTE_QN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    11-Nov-2018 18:16:00

dphi = in1(10,:);
dpsi = in1(12,:);
dtheta = in1(11,:);
dx = in1(7,:);
dy = in1(8,:);
dz = in1(9,:);
phi = in1(4,:);
psi = in1(6,:);
theta = in1(5,:);
x = in1(1,:);
xf_1 = in2(1,:);
xf_2 = in2(2,:);
xf_3 = in2(3,:);
xf_4 = in2(4,:);
xf_5 = in2(5,:);
xf_6 = in2(6,:);
xf_7 = in2(7,:);
xf_8 = in2(8,:);
xf_9 = in2(9,:);
xf_10 = in2(10,:);
xf_11 = in2(11,:);
xf_12 = in2(12,:);
y = in1(2,:);
z = in1(3,:);
t2 = phi-xf_4;
t3 = psi-xf_6;
t4 = theta-xf_5;
t5 = x-xf_1;
t6 = xf_2-y;
t7 = xf_3-z;
t8 = dphi-xf_10;
t9 = dpsi-xf_12;
t10 = dtheta-xf_11;
t11 = dx-xf_7;
t12 = dy-xf_8;
t13 = dz-xf_9;
qN = t2.^2+t3.^2+t4.^2+t5.^2+t6.^2+t7.^2+t8.^2+t9.^2+t10.^2+t11.^2+t12.^2+t13.^2;
