function r = compute_r_vec(t,in2,in3,in4,in5,in6,t_wp)
%COMPUTE_R_VEC
%    R = COMPUTE_R_VEC(T,IN2,IN3,IN4,IN5,IN6,T_WP)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    05-Nov-2018 19:02:01

r = [0.0;0.0;0.0;0.0];
