function qN = compute_qN(in1)
%COMPUTE_QN
%    QN = COMPUTE_QN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    05-Nov-2018 17:57:26

dp = in1(11,:);
dr = in1(10,:);
dx = in1(7,:);
dy = in1(8,:);
dyaw = in1(12,:);
dz = in1(9,:);
p = in1(5,:);
r = in1(4,:);
x = in1(1,:);
y = in1(2,:);
yaw = in1(6,:);
z = in1(3,:);
qN = (x.*1.0e4-1.0e4).*(x-1.0)+(y.*1.0e4-1.0e4).*(y-1.0)+(z.*1.0e4-1.0e4).*(z-1.0)+dp.^2.*1.0e4+dr.^2.*1.0e4+dx.^2.*1.0e4+dy.^2.*1.0e4+dyaw.^2.*1.0e4+dz.^2.*1.0e4+p.^2.*1.0e4+r.^2.*1.0e4+yaw.^2.*1.0e4;
