function qN_vec = compute_qN_vec(in1,in2)
%COMPUTE_QN_VEC
%    QN_VEC = COMPUTE_QN_VEC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    07-Nov-2018 15:25:47

dp = in1(11,:);
dr = in1(10,:);
dx = in1(7,:);
dy = in1(8,:);
dyaw = in1(12,:);
dz = in1(9,:);
p = in1(5,:);
r = in1(4,:);
x = in1(1,:);
xf_1 = in2(1,:);
xf_2 = in2(2,:);
xf_3 = in2(3,:);
xf_4 = in2(4,:);
xf_5 = in2(5,:);
xf_6 = in2(6,:);
xf_7 = in2(7,:);
xf_8 = in2(8,:);
xf_9 = in2(9,:);
xf_10 = in2(10,:);
xf_11 = in2(11,:);
xf_12 = in2(12,:);
y = in1(2,:);
yaw = in1(6,:);
z = in1(3,:);
qN_vec = [x.*2.0e6-xf_1.*2.0e6;xf_2.*-2.0e6+y.*2.0e6;xf_3.*-2.0e6+z.*2.0e6;r.*2.0e6-xf_4.*2.0e6;p.*2.0e6-xf_5.*2.0e6;xf_6.*-2.0e6+yaw.*2.0e6;dx.*2.0e6-xf_7.*2.0e6;dy.*2.0e6-xf_8.*2.0e6;dz.*2.0e6-xf_9.*2.0e6;dr.*2.0e6-xf_10.*2.0e6;dp.*2.0e6-xf_11.*2.0e6;dyaw.*2.0e6-xf_12.*2.0e6];
