function P = compute_P(t,in2,in3,in4,t_wp)
%COMPUTE_P
%    P = COMPUTE_P(T,IN2,IN3,IN4,T_WP)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    05-Nov-2018 16:34:04

P = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[4,12]);
