function q = compute_q(in1,in2)
%COMPUTE_Q
%    Q = COMPUTE_Q(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    27-Oct-2018 23:47:57

dp = in1(11,:);
dr = in1(10,:);
dx = in1(7,:);
dy = in1(8,:);
dyaw = in1(12,:);
dz = in1(9,:);
p = in1(5,:);
r = in1(4,:);
u1 = in2(1,:);
u2 = in2(2,:);
u3 = in2(3,:);
u4 = in2(4,:);
u5 = in2(5,:);
u6 = in2(6,:);
x = in1(1,:);
y = in1(2,:);
yaw = in1(6,:);
z = in1(3,:);
t2 = x-1.0;
t3 = y-1.0;
t4 = z-1.0;
q = dp.^2+dr.^2+dx.^2+dy.^2+dyaw.^2+dz.^2+p.^2+r.^2+t2.^2+t3.^2+t4.^2+u1.^2+u2.^2+u3.^2+u4.^2+u5.^2+u6.^2+yaw.^2;
