function qN = compute_qN(in1)
%COMPUTE_QN
%    QN = COMPUTE_QN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    27-Oct-2018 23:35:28

dp = in1(11,:);
dr = in1(10,:);
dx = in1(7,:);
dy = in1(8,:);
dyaw = in1(12,:);
dz = in1(9,:);
p = in1(5,:);
r = in1(4,:);
x = in1(1,:);
y = in1(2,:);
yaw = in1(6,:);
z = in1(3,:);
t2 = x-1.0;
t3 = y-1.0;
t4 = z-1.0;
qN = dp.^2+dr.^2+dx.^2+dy.^2+dyaw.^2+dz.^2+p.^2+r.^2+t2.^2+t3.^2+t4.^2+yaw.^2;
