function R = compute_R_mat(t,in2,in3,in4,t_wp)
%COMPUTE_R_MAT
%    R = COMPUTE_R_MAT(T,IN2,IN3,IN4,T_WP)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    30-Oct-2018 23:58:47

R = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0],[6,6]);
